spring:
  application:
    name: api-gateway
server:
  port: 5555
zuul:
  routes:
    api-a-url:
      path: /api-a-url/**
      url: http://localhost:8080
    api-b-url:
      path: /api-b-url/**
      url: http://localhost:8081
    api-c-url:
      path: /api-c/url/**
      url: http://localhost:9000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/,http://localhost:1112/eureka/