
server:
  port: 7500
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/WuMenghao/clouddemo/
          username: WuMenghao
          password: tmwmh023328
          search-paths: tree/master/config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/,http://localhost:1112/eureka/